services:
  backend:
    build: ./backend
    container_name: em_backend_container
    restart: always
    networks:
      - em_network

  nginx:
    image: nginx:latest
    container_name: em_nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - em_network

networks:
  em_network:
    driver: bridge
